name: Process Dicts

on:
  # 可以手动触发
  workflow_dispatch:
  # 定时运行(每周五晚18点)
  schedule:
    - cron: '0 18 * * 5'
  # 推送到特定分支时触发
  # push:
  #   branches: [ main ]

jobs:
  process-and-commit:
    runs-on: ubuntu-latest
    
    # 设置仓库写入权限
    permissions:
      contents: write
    
    steps:
      # 1. 迁出仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # 使用 GitHub Token 进行认证
          token: ${{ secrets.GITHUB_TOKEN }}
          # 如果需要在同一分支上提交，设置 fetch-depth: 0 获取完整历史
          fetch-depth: 0
      
      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'    # 指定Python版本
          cache: 'pip'              # 缓存依赖以加速后续运行
      
      # 3. 从指定位置下载文件
      - name: Download file
        run: |
          # 设置pip, 加载依赖
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          # 创建下载目录
          mkdir -p downloads
          
          # 从指定 URL 下载文件
          # 请替换为你的实际下载 URL
          if ! curl -f -L -o downloads/zi.dict.yaml "https://raw.githubusercontent.com/amzxyz/RIME-LMDG/refs/heads/wanxiang/dicts/zi.dict.yaml"; then
            echo "::error::CURL DOWNLOAD FAILED at $(date)"
          fi
          echo "Download zi dict completed"
          if ! curl -f curl -L -o downloads/jichu.dict.yaml "https://raw.githubusercontent.com/amzxyz/RIME-LMDG/refs/heads/wanxiang/dicts/jichu.dict.yaml"; then
            echo "::error::CURL DOWNLOAD FAILED at $(date)"
          fi
          echo "Download jichu dict completed"
          if ! curl -f -L -o downloads/lianxiang.dict.yaml "https://raw.githubusercontent.com/amzxyz/RIME-LMDG/refs/heads/wanxiang/dicts/lianxiang.dict.yaml"; then
            echo "::error::CURL DOWNLOAD FAILED at $(date)"
          fi
          echo "Download lianxiang dict completed"
      
      # 4. 运行 Python 程序处理文件
      - name: Run Python program
        run: |
          mkdir -p dicts
          python replace_tone.py dicts/test.dict.yaml dicts/test.dict.yaml
          python replace_tone.py downloads/zi.dict.yaml dicts/zi.dict.yaml
          python replace_tone.py downloads/jichu.dict.yaml dicts/jichu.dict.yaml
          python replace_tone.py downloads/lianxiang.dict.yaml dicts/lianxiang.dict.yaml
      
      # 5. 配置 Git 用户信息
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      # 6. 将生成的输出文件提交到仓库
      - name: Commit & Push
        run: |
          # 删除临时文件夹
          rm -rf downloads

          # 检查是否有新文件或修改
          # git add dicts/
          
          # 检查是否有变更
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          # 提交变更
          git commit -m "Update processed dicts from workflow run $(date +'%Y-%m-%d %H:%M:%S')"
          # 推送到仓库
          git push origin HEAD:${GITHUB_REF#refs/heads/}

          
